# Generated by Django 2.0.4 on 2018-10-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitals',
            name='id',
        ),
        migrations.AddField(
            model_name='hospitals',
            name='hospital_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
