# Generated by Django 2.0.4 on 2018-10-07 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20181007_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='age',
            field=models.CharField(default=20, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patients',
            name='gender',
            field=models.CharField(default='UNK', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patients',
            name='hospital',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='patients.Hospitals'),
            preserve_default=False,
        ),
    ]
