# Generated by Django 2.0.4 on 2018-10-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patients_whats_wrong'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='time_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
