# Generated by Django 2.0.4 on 2018-10-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patients_time_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='img1',
            field=models.CharField(default='', max_length=100000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patients',
            name='img2',
            field=models.CharField(default='', max_length=100000),
            preserve_default=False,
        ),
    ]
